# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_catch22.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_custom0.25.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_256/TSFRESH_OBSEA_256_minimal.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_catch22.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_custom0.25.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_512/TSFRESH_OBSEA_512_minimal.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_catch22.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_catch22_not_normalized/ #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_custom0.25.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# ython3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
# python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_768/TSFRESH_OBSEA_768_minimal.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_minimal_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=knn --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=svc_linear --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=decision_tree --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=random_forest --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=mlp --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=ada_boost --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=bayes --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
python3.8 train_feature_based.py --path=data/not_normalized/OBSEA_1024/TSFRESH_OBSEA_1024_custom0.25.npy --classifier=qda --file=reproducibility_guide/train_val_split.csv --path_save=results/weights/weights_custom0.25_not_normalized/  #--eval-true
